# See: https://taskfile.dev/api/

version: "3"

tasks:
  migrate:
    aliases:
      - migrate
    desc: "Make migrations"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
